#!/bin/bash
set -e

# root123456 Root1234*

apt update

# General
apt install -y chrome-gnome-shell nautilus-dropbox nemo virtualbox-qt rar unrar vlc composer  openssh-server kolourpaint4 filezilla chromium-browser gedit gimp git flashplugin-installer meld gnupg sublime-text  

# LAMP
apt install -y apache2 mysql-server mysql-client php libapache2-mod-php
mysql_secure_installation
echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf
clear
echo "On another terminal, run 'sudo mysql' and run following query:"
echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '[your mysql password here]';"
echo ""
read -p "Hit enter when done: " X
#mysql || true
apt install -y phpmyadmin  
echo "\$cfg['SendErrorReports'] = 'never';" >> /etc/phpmyadmin/config.inc.php 
service apache2 restart
# sudo dpkg-reconfigure phpmyadmin To reconfigure 

### Localhost
echo "<?php phpinfo();" > index.php
mv index.php /var/www/html || true
mv /var/www/html/index.html /var/www/html/index.apache.html || true
gedit /etc/php/7.4/apache2/php.ini
service apache2 restart

read -p "All Done. Hit anything on <enter> key to exit. " X 
exit 0

