#!/bin/bash
set -e

read -p "Enter your username: " N 

apt update

# General
apt install -y flameshot xclip npm expect activity-log-manager chrome-gnome-shell nautilus-dropbox nemo virtualbox-qt rar unrar vlc composer  openssh-server kolourpaint4 filezilla chromium-browser gedit gimp git flashplugin-installer meld gnupg sublime-text  

# Apache, PHP, MySQL
apt install -y apache2 mysql-server mysql-client php libapache2-mod-php

mkdir -p /home/$N/www
echo "<?php phpinfo();" > /home/$N/www/index.php 

if [ ! -f /etc/apache2/apache2.conf.default ]; then
    cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf.default
fi
echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf 
sed -i "s|<Directory /var/www/>|<Directory /home/$N/www/>|g" /etc/apache2/apache2.conf
sed -i "172s|AllowOverride None|AllowOverride All|g" /etc/apache2/apache2.conf

if [ ! -f /etc/apache2/sites-available/000-default.conf.default ]; then
    cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf.default
fi
sed -i "s|DocumentRoot /var/www/html|DocumentRoot /home/$N/www|g" /etc/apache2/sites-available/000-default.conf

if [ ! -f /etc/apache2/envvars.default ]; then
    cp /etc/apache2/envvars /etc/apache2/envvars.default
fi
sed -i "s/www-data/$N/g" /etc/apache2/envvars

if [ ! -f /etc/php/7.4/apache2/php.ini.default ]; then
    cp /etc/php/7.4/apache2/php.ini /etc/php/7.4/apache2/php.ini.default
fi 
sed -i "s/display_errors = Off/display_errors = On/g" /etc/php/7.4/apache2/php.ini
sed -i "s/post_max_size = 8M/post_max_size = 8000M/g" /etc/php/7.4/apache2/php.ini
sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 8000M/g" /etc/php/7.4/apache2/php.ini

mysql_secure_installation 
mysql -u root -p'root' -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" 

# phpMyAdmin
apt install -y phpmyadmin  
# sudo dpkg-reconfigure phpmyadmin

if [ ! -f /etc/phpmyadmin/config.inc.php.default ]; then
    cp /etc/phpmyadmin/config.inc.php /etc/phpmyadmin/config.inc.php.default
fi
echo "\$cfg['SendErrorReports'] = 'never';" >> /etc/phpmyadmin/config.inc.php 

service apache2 restart

# Python
apt install python3-pip
alias python='python3'
alias pip='pip3'
pip install requests yfinance pandas streamlit

# NodeJS
apt-get install curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get install nodejs
npm install npm@latest -g

# yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
apt-get update
apt-get install yarn


read -p "All Done. Hit anything on <enter> key to exit. " X 
exit 0

