#!/bin/bash 

sudo apt update &&

# -------------------------------------------------
# Common Stuff
# -------------------------------------------------
sudo apt-get install -y gparted rar unrar vlc gedit composer audacity tesseract-ocr xclip eog sublime-text etherape pyrenamer activity-log-manager kolourpaint4 kget filezilla chromium-browser expect gimp git scrot flashplugin-installer meld  gnupg fswebcam python-xlib nautilus-dropbox imagemagick terminator python-pip && 
# openjdk-7-jdk (not available on Linux Mint 18 Sarah)



# -------------------------------------------------
# LAMP Stack w/ PHPMyAdmin
# -------------------------------------------------
sudo apt-get install -y mysql-server mysql-client apache2 php7.0 libapache2-mod-php7.0 &&
sudo service apache2 restart &&
sudo apt-get install -y php7.0-mysql php-gettext php7.0-curl php7.0-gd php-pear php-imagick php7.0-imap php7.0-mcrypt php-memcache php7.0-ps php7.0-pspell php7.0-recode php7.0-snmp php7.0-sqlite php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-mcrypt &&
# php7.0-idn php7.0-ming # these didn't found in mint-18 php-idn, php-ming also didn't work
sudo service apache2 restart &&
sudo apt-get install -y phpmyadmin &&
sudo service apache2 restart &&
sudo apt-get --reinstall install -y php7.0-mcrypt &&
sudo service apache2 restart &&
sudo phpenmod mcrypt && 
sudo apt remove php7.0-snmp &&

# -------------------------------------------------
# PHP Info
# -------------------------------------------------
echo "<?php phpinfo(); ?>" >> /var/www/html/info.php && 

# -------------------------------------------------
# PHP ini & PHPMyAdmin Settings, Enable some
# Extensions
# -------------------------------------------------
clear &&
echo 'Adjust some settings in opening file and close editor once done.' &&
sudo gedit /etc/php/7.0/apache2/php.ini &&
#    upload_max_filesize
#    post_max_size
#    display_errors
sudo a2enmod rewrite &&
sudo service apache2 restart &&
clear &&
echo 'Add `Include /etc/phpmyadmin/apache.conf` at end of the opening file and close editor once done.' &&
sudo gedit /etc/apache2/apache2.conf && #Include /etc/phpmyadmin/apache.conf
sudo service apache2 restart &&
mysql -u root -p'root' -e 'SET @@GLOBAL.sql_mode = ""' &&


# -------------------------------------------------
# Node JS 
# ------------------------------------------------- 
sudo apt install nodejs npm node-express-generator &&
sudo ln -s /usr/bin/nodejs /usr/bin/node && 
sudo npm install mysql && # use --save to add into dependencies as well
sudo npm install cors && # cross-origin resource sharing. use --save to add into dependencies as well
sudo npm install bower -g &&


# -------------------------------------------------
# Links. These can be yours too. Add whatever you wish
# ------------------------------------------------- 
ln -s ~/Dropbox/Evernote/Linux/Scripts/ ~/scripts &&
ln -s ~/Dropbox/Official/SSH/ ~/ssh



